ENCODER_MAP_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306

WPM_ENABLE = yes
RGBLIGHT_ENABLE = no
RGBLIGHT_ANIMATIONS = no

CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
STENO_ENABLE = no
TERMINAL_ENABLE = no
GRAVE_ESC_ENABLE = no
AUDIO_ENABLE = no
VELOCIKEY_ENABLE = no
SWAP_HANDS_ENABLE = no

LTO_ENABLE = yes
